// Export all pages for easier imports
export { default as Home } from './Home'
export { default as Shop } from './Shop'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Cart } from './Cart'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Dashboard } from './Dashboard'
export { default as Orders } from './Orders'
export { default as AccountSettings } from './AccountSettings'
export { default as PrivacyPolicy } from './PrivacyPolicy'
export { default as TermsConditions } from './TermsConditions'
